name: Publish Markdown Files
env:
  VERCEL_ORG_ID: matthewwong525 # TODO: Change this
  VERCEL_PROJECT_ID: linked-blog-md # TODO: Change this
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: md
    - name: Checkout linked blog starter repo
      uses: actions/checkout@v3
      with:
        repository: matthewwong525/linked-blog-starter
        path: blog
    - name: Install Rust / cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install and run obsidian-export
      run: |
        cargo install obsidian-export
        ~/.cargo/bin/obsidian-export md blog/_commonMD
    - name: Install Vercel & Deploy
      run: |
        cd blog
        npm install --global vercel@latest
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}