name: Publish Markdown Files
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Checkout linked blog starter repo
      uses: actions/checkout@v3
      with:
        repository: matthewwong525/linked-blog-starter
        path: main
    - name: Install obsidian-export
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: ls
    - run: cargo install obsidian-export
    - run: ~/.cargo/bin/obsidian-export